blog/urls.py
from unicodedata import name
from urllib.parse import urlparse
from django.urls import path
from .views import BlogListView,BlogCreateView, BlogdetailView,BlogUpdateView,BlogDeleteView

app_name='blog'

urlpatterns = [
    
    path('',BlogListView.as_view(),name='home'),#?creamos la vista listar y se la asignamos a la url de blog
    path('create/',BlogCreateView.as_view(),name='create'), #?creamos la vista a create y se la asignamos a la url de blog
    path('<int:pk>/',BlogdetailView.as_view(),name='detail'), #?Creamos la vista detalle del blog
    path('<int:pk>/update/',BlogUpdateView.as_view(),name='update'), #?en esta url actualizamos
    path('<int:pk>/delete/',BlogDeleteView.as_view(),name='delete'), #?en esta url eliminamos
    
]

core/urls.py
from django.contrib import admin
from django.urls import path,include

from .views import HomeView

urlpatterns = [
    
    
    path('admin/', admin.site.urls),
    
    path("__reload__/", include("django_browser_reload.urls")),
    
    path('',HomeView.as_view(),name='home'),
    
    path('blog/',include('blog.urls',namespace='blog')),
    
   
    
]

blog/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title=models.CharField(max_length=250)
    content=models.TextField()

    def __str__(self):
        return self.title
    

blog/forms.py
# todo: Formulario

# !libreria de django para formularios
from dataclasses import field, fields
from django import forms

# !traemos el modelo de blogs
from .models import Post


# !Formulario para crear un post desde la vista a la BBDD
class PostCreateForm(forms.ModelForm):
    class Meta:
        model=Post # *traemos el modelo
        fields=('title','content') # *traemos los campos del modelo
            

blog/views.py
# todo: Vistas

from django.shortcuts import render,redirect,get_object_or_404,redirect
from django.views.generic import View, UpdateView, DeleteView

#! traemos la clase de froms.py PostCreateForm
from .forms import PostCreateForm
from .models import Post

#! importamos de django
from django.urls import reverse_lazy


#todo esta clase es para listar los blog
class BlogListView(View):
    def get(self,request,*args, **kwargs):
        posts = Post.objects.all()
        context = {
            'posts':posts
        }
        return render(request,'blog_list.html',context)


#todo esta clase crea la vista al BlogCreateView
class BlogCreateView(View):
    
    def get(self,request,*args, **kwargs):
        form=PostCreateForm() #?pasamos la clase form de traida de forms.py a una variable llamada form
        context={
            'form':form
        }
        return render(request,'blog_create.html',context)
    
    #todo el get los cambiamos a post dentro de la misma clase
    def post(self,request,*args, **kwargs):
        
        if request.method == "POST": #?si el metodo es post
            form=PostCreateForm(request.POST) #? traeme el formulario y toda la info que esta dentro de post(request.POST) en el formulario en la pagina create
            
            if form.is_valid(): #? si el formulario es valido obtenemos el titulo y el contenido la info que ingresamos en la pagina create
                title = form.cleaned_data.get('title') #? aqui obtenemos lo que ingresamos en el campo title del formulario
                content = form.cleaned_data.get('content') #? aqui obtenemos lo que ingresamos en el campo content del formulario
                
                
                p,created = Post.objects.get_or_create(title=title, content=content) #? Al modelo Post (BBDD) le asiganamos lo que tenemos en el formulario
                p.save() #? guardamos la informacion en el modelo de la BBDD
                return redirect('blog:home') #? lo redireccionamos al home
            
        context={
            
        }
        return render(request,'blog_create.html',context)
    
    
#todo esta clase crea el detalle del blog   
class BlogdetailView(View):
    def get(self,request,pk,*args, **kwargs):
        post = get_object_or_404(Post, pk=pk) #?creamos el objeto post y llamamos al modelo Post y su prymary key = pk,
                                              #?y la igualamos con la que viene de la url --> path('<int:pk>/',BlogdetailView.as_view(),name='detail')
        context = {
            'post':post
        }
        return render(request,'blog_detail.html',context)
    
#todo esta clase actualizara el blog
class BlogUpdateView(UpdateView):
    model = Post  #? le pasamos el modelo que queremos editar
    fields=['title','content'] #? pasamos los campos que queremos editar
    template_name='blog_update.html' #? lo enviamos al blog_update.html
    
    def get_success_url(self):     #? una vez lo actualizamos lo redireccionamos al blog:detail
        pk = self.kwargs['pk'] #?creamos un objeto del modelo Post ese objeto es self y traemos la kwargs y su campo pk
        return reverse_lazy('blog:detail', kwargs={'pk':pk})
    
#todo esta clase borra un blog
class BlogDeleteView(DeleteView):
    model = Post  #? le pasamos el modelo que queremos editar
    template_name='blog_delete.html' #? lo enviamos al blog_delete.html
    success_url= reverse_lazy('blog:home')

core/views.py
from django.shortcuts import render
from django.views.generic import View

class HomeView(View):
    def get(self,request, *args, **kwargs):
        context={
            
        }
        return render(request,'index.html',context)
        

templates/base.html
{% load tailwind_tags %}
<!-- <!doctype html> -->
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Welcome | {% block title %}
      
      
    {% endblock title %}</title>
    {% tailwind_css %}
  </head>
  <body class="h-screen bg-white-600 flex justify-center items-center space-x-4">
   

    <div class="container">
        {% block content %}
          

        {% endblock content %}
    </div>

    <div class="container">

       
    </div>
    
  </body>
</html>

templates/blog_create.html
{% extends "base.html" %} 

{% block title %}
  Creacion
{% endblock title %}

{% block content %}

<form method="POST">
  {% csrf_token %}
 
      {{form.title}}
  
  
    {{form.content}}
  
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

<a href="{% url 'blog:home' %}">Volver</a>
{% endblock content %}

templates/blog_delete.html
{% extends "base.html" %} 

{% block title %}
  Eliminar un Blog
{% endblock title %}

{% block content %}
<p>Are you sure?</p>
<form method="POST">
  {% csrf_token %}
  {{form}}
  <button type="submit" class="btn btn-primary">Delete</button>
</form>
{% endblock content %}

templates/blog_detail.html
{% extends "base.html" %}

{% block title %}
  Detalle del Blog
{% endblock title %}
    
{% block content %}

{{post.title}}
<br>
{{post.content}}
<br>
<a href="{% url 'blog:home' %}">Home</a>
{% endblock content %}

templates/blog_list.html
{% extends "base.html" %}

{% block title %}
  Blog
{% endblock title %}
    
{% block content %}


{% for post in posts  %}
<a href="{% url 'blog:detail' post.id%}"> {{post.title}} </a> 
<a href="{% url 'blog:update' post.id %}"> update</a>
<a href="{% url 'blog:delete' post.id %}">Eliminar</a>
 <br>
{% endfor %}


<br>
<a class="bg-blue-300 px-4 py-3 rounded" href="{% url 'blog:create' %}">Create</a>
<a class="bg-orange-300 px-4 py-3 rounded" href="{% url 'home' %}">Home</a>
{% endblock content %}

  

templates/blog_update.html
{% extends "base.html" %} 

{% block title %}
  Actualizacion
{% endblock title %}

{% block content %}

<form method="POST">
  {% csrf_token %}
 
      {{form.title}}
  
  
    {{form.content}}
  
  <button type="submit" class="btn btn-primary">Actualizar</button>
</form>

<a href="{% url 'blog:home' %}">Volver</a>
{% endblock content %}

templates/index.html
{% extends "base.html" %}

{% block title %}
  Inicio
{% endblock title %}

{% block content %}
  <h1>Hola Gonzalo</h1>



  Visita mi <a class="text-red-500" href="{% url 'blog:home' %}">Blog aquí</a>


  
{% endblock content %}

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>